import { LanguageProvider } from "@/context/LanguageContext";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "AL-SAND",
//   description: "Generated by create next app",
// };

export const metadata = {
  title: "سند للعقار | مكتب عقاري في بغداد – المنصور شارع الأميرات",
  description:
    "مكتب السند للعقار في بغداد يقدم خدمات بيع وشراء وتأجير العقارات السكنية والتجارية في المنصور وشارع الأميرات وباقي مناطق بغداد. خبرة، مصداقية، وإنجاز سريع للمعاملات العقارية.",
  keywords: [
    "سند للعقار",
    "مكتب عقار بغداد",
    "عقارات بغداد",
    "مكتب عقاري في المنصور",
    "عقارات المنصور",
    "شارع الأميرات",
    "بيع شراء عقارات بغداد",
    "تأجير بيوت بغداد",
    "أراضي للبيع بغداد",
    "مكاتب عقارية بغداد",
  ],
  authors: [{ name: "السند للعقار" }],
  creator: "السند للعقار",
  publisher: "السند للعقار",
  metadataBase: new URL("https://sanadd.com"), // غيّرها إذا عندك دومين ثاني
  openGraph: {
    title: "سند للعقار | مكتب عقاري في بغداد – المنصور",
    description:
      "السند للعقار مكتب مختص ببيع وشراء وتأجير العقارات في بغداد، المنصور، شارع الأميرات. خدمات عقارية موثوقة وأسعار تنافسية.",
    url: "https://sanadd.com",
    siteName: "السند للعقار",
    locale: "ar_IQ",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "السند للعقار | مكتب عقاري في بغداد",
    description:
      "مكتب السند للعقار – خبرة في بيع وشراء وتأجير العقارات في بغداد، المنصور، شارع الأميرات.",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@100;200;300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LanguageProvider>{children}</LanguageProvider>
      </body>
    </html>
  );
}
