import { LanguageProvider } from "@/context/LanguageContext";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "AL-SAND",
//   description: "Generated by create next app",
// };

export const metadata = {
  icons: {
    icon: "/images/logos/we.png",
    apple: "/images/logos/we.png",
    appleIos: "/images/logos/we.png",
    appleStartup: "/images/logos/we.png",
    favicon: "/images/logos/we.png",
    faviconPrecomposed: "/images/logos/we.png",
  },
  title: "سند للعقار | أفضل مكتب عقاري في بغداد المنصور - بيع شراء تأجير",
  description:
    "مكتب سند للعقار في بغداد (السند) خبيرك الأول في المنصور، شارع الأميرات، واليرموك. نوفر أرقى الفلل، الشقق، الأراضي، والمجمعات السكنية. بيع، شراء، وتأجير بمصداقية عالية وإنجاز معاملات قانونية سريع.",
  keywords: [
    // --- اسم المكتب وتفرعاته ---
    "سند",
    "السند",
    "سند للعقار",
    "مكتب سند للعقار",
    "مكتب السند",
    "شركة سند للعقار",
    "Sanad",
    "Sanad Real Estate",
    "سند عقارات",

    // --- المواقع الجغرافية (تغطية شاملة) ---
    "عقارات بغداد",
    "عقارات المنصور",
    "عقارات شارع الأميرات",
    "عقارات اليرموك",
    "عقارات حي الجامعة",
    "عقارات حي الحارثية",
    "عقارات القادسية",
    "عقارات حي العدل",
    "عقارات الكرخ",
    "عقارات شارع 14 رمضان",
    "عقارات الداوودي",
    "عقارات نفق الشرطة",
    "عقارات العامرية",
    "عقارات الخضراء",

    // --- نوع الخدمة (كلمات بيع وشراء) ---
    "بيع عقارات بغداد",
    "شراء عقارات بغداد",
    "تأجير بيوت بغداد",
    "إيجار شقق المنصور",
    "بيوت للبيع في المنصور",
    "شقق للبيع في بغداد",
    "أراضي للبيع في بغداد",
    "محلات للايجار في بغداد",
    "مكاتب تجارية للايجار المنصور",
    "عقارات تجارية بغداد",
    "استثمار عقاري في العراق",
    "شقق مؤثثة للايجار بغداد",

    // --- كلمات عامة وشعبية (لأرشفة قوية) ---
    "دلال عقارات",
    "مكتب دلالية بغداد",
    "مكتب عقار",
    "مكاتب عقارية في المنصور",
    "سعر المتر في المنصور",
    "طابو ملك صرف",
    "بيوت طابو زراعي",
    "خارطة بغداد العقارية",
    "دليل عقارات العراق",
    "تطبيق عقارات العراق",
    "أفضل مكتب عقار في بغداد",
    "أرخص شقق في بغداد",
    "فلل فاخرة للبيع بغداد",
    "قصور للبيع في شارع الأميرات",

    // --- معاملات وقوانين ---
    "تسجيل عقاري",
    "نقل ملكية عقار",
    "إجازة بناء",
    "تقدير سعر العقار",
    "خبير عقاري بغداد",
  ],
  viewport: {
    themeColor: "#000000",
  },

  authors: [{ name: "سند للعقار - Sanad Real Estate" }],
  creator: "سند للعقار",
  publisher: "سند للعقار",
  metadataBase: new URL("https://sanadd.com"),

  openGraph: {
    title: "مكتب سند للعقار | خبير العقارات في المنصور وشارع الأميرات",
    description:
      "هل تبحث عن بيت أحلامك في بغداد؟ مكتب سند يوفر لك أفضل الفرص العقارية في المنصور وأرقى مناطق الكرخ. بيع، شراء، واستثمار.",
    url: "https://sanadd.com",
    siteName: "سند للعقار - Sanad Real Estate",
    locale: "ar_IQ",
    type: "website",
    images: [
      {
        url: "/images/logos/we.png",
        width: 1200,
        height: 630,
        alt: "سند للعقار - Baghdad Real Estate",
      },
    ],
  },

  twitter: {
    card: "summary_large_image",
    title: "سند للعقار | Sanad Real Estate",
    description:
      "تغطية شاملة لعقارات بغداد، المنصور، وشارع الأميرات. أفضل الأسعار وأرقى العقارات.",
    images: ["/images/logos/we.png"],
  },

  alternates: {
    canonical: "https://sanadd.com",
  },

  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@100;200;300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LanguageProvider>{children}</LanguageProvider>
      </body>
    </html>
  );
}
